fragment BiographyFragment on BiographyRecord {
  __typename
  id
  navigationId
  fadeIn
  image {
    responsiveImage(
      imgixParams: { fit: crop, w: "440", h: "590", fm: avif, auto: compress }
    ) {
      ...responsiveImageFragment
    }
  }
  bioDescription {
    value
    blocks {
      id
      title
      subtitle
    }
  }
}
