fragment HeroFragment on HeroRecord {
  __typename
  id
  navigationId
  image {
    responsiveImage(imgixParams: { fit: crop, auto: compress, fm: avif }) {
      ...responsiveImageFragment
    }
  }
  backgroundImage {
    responsiveImage(imgixParams: { fit: crop, auto: compress, fm: avif }) {
      ...responsiveImageFragment
    }
  }
  buttonText
  buttonLink
}
