fragment FooterFragment on FooterRecord {
  __typename
  id
  navigationId
  address {
    value
  }
  contact {
    value
  }
  location {
    latitude
    longitude
  }
  openingHours {
    value
  }
  info {
    value
  }
}
