fragment ImageFragment on ImageRecord {
  __typename
  navigationId
  backgroundColor
  fadeIn
  imageTitle
  image {
    responsiveImage(imgixParams: { fit: crop, auto: compress, fm: avif }) {
      ...responsiveImageFragment
    }
  }
}
