query CustomColor {
  layout {
    primaryColor {
      red
      green
      blue
    }
    secondaryColor {
      red
      green
      blue
    }
    accentColor {
      red
      green
      blue
    }
  }
}
