query HomePage {
  site: _site {
    favicon: faviconMetaTags {
      ...metaTagsFragment
    }
  }
  page {
    seo: _seoMetaTags {
      ...metaTagsFragment
    }
    id
    name
    primaryColor {
      red
      green
      blue
    }
    secondaryColor {
      red
      green
      blue
    }
    accentColor {
      red
      green
      blue
    }
    instagramUrl
    facebookUrl
    content {
      ... on HeroRecord {
        ...HeroFragment
      }
      ... on TextRecord {
        ...TextFragment
      }
      ... on ImageRecord {
        ...ImageFragment
      }
      ... on TextImageRecord {
        ...TextImageFragment
      }
      ... on GridRecord {
        ...GridFragment
      }
      ... on YoutubeVideoRecord {
        ...YoutubeVideoFragment
      }
      ... on HairMenuRecord {
        ...HairMenuFragment
      }
      ... on BiographyRecord {
        ...BiographyFragment
      }
      ... on FooterRecord {
        ...FooterFragment
      }
    }
  }
}
