query HomePage {
  site: _site {
    favicon: faviconMetaTags {
      ...metaTagsFragment
    }
  }
  introPage {
    seo: _seoMetaTags {
      ...metaTagsFragment
    }
    leftLink {
      name
      slug
    }
    leftLogo {
      responsiveImage(imgixParams: { fit: crop, auto: format }) {
        ...responsiveImageFragment
      }
    }
    leftIntro {
      value
    }
    leftShowIntro
    leftColor {
      red
      green
      blue
    }
    rightLink {
      name
      slug
    }
    rightLogo {
      responsiveImage(imgixParams: { fit: crop, auto: format }) {
        ...responsiveImageFragment
      }
    }
    rightIntro {
      value
    }
    rightShowIntro
    rightColor {
      red
      green
      blue
    }
  }
}
