query PageBySlug($slug: String) {
  site: _site {
    favicon: faviconMetaTags {
      ...metaTagsFragment
    }
  }
  page(filter: { slug: { eq: $slug } }) {
    seo: _seoMetaTags {
      ...metaTagsFragment
    }
    id
    name
    slug
    content {
      ... on HeaderRecord {
        ...HeaderFragment
      }
      ... on TextRecord {
        ...TextFragment
      }
      ... on ImageRecord {
        ...ImageFragment
      }
      ... on TextImageRecord {
        ...TextImageFragment
      }
      ... on GridRecord {
        ...GridFragment
      }
      ... on YoutubeVideoRecord {
        ...YoutubeVideoFragment
      }
      ... on HairMenuRecord {
        ...HairMenuFragment
      }
      ... on BiographyRecord {
        ...BiographyFragment
      }
      ... on FooterRecord {
        ...FooterFragment
      }
    }
  }
  allPages {
    id
    name
    slug
  }
  introPage {
    seo: _seoMetaTags {
      ...metaTagsFragment
    }
    leftLink {
      name
      slug
    }
    leftLogo {
      responsiveImage(
        imgixParams: {
          fit: crop
          crop: focalpoint
          ar: "1:1"
          minH: 384
          auto: format
        }
      ) {
        ...responsiveImageFragment
      }
    }
    leftLogoType
    rightLink {
      name
      slug
    }
    rightLogo {
      responsiveImage(
        imgixParams: {
          fit: crop
          crop: focalpoint
          ar: "1:1"
          minH: 384
          auto: format
        }
      ) {
        ...responsiveImageFragment
      }
    }
    rightLogoType
  }
}
