fragment GridTextFragment on GridTextRecord {
  __typename
  id
  mobilePosition
  tabletPosition
  desktopPosition
  content {
    value
    blocks {
      __typename
      ... on RtImageRecord {
        ...RtImageFragment
      }
    }
  }
}
